repos:
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/lyz-code/autoimport/
    rev: 1.3.3
    hooks:
    -   id: autoimport
-   repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.0.270
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-toml
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
        args: [--fix=no]
    -   id: end-of-file-fixer
